name: Signin Task

on:

  #workflow_dispatch:
  
  schedule:
    - cron: '01 16 * * *'

jobs:
  Run-Signin-Task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.8'

      - name: Install CFFI
        run: pip install requests curl_cffi

      - name: Run Task
        env:
          COOKIE: ${{ secrets.COOKIE }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python task.py
        
      - name: Delete Workflow History
        uses: ophub/delete-releases-workflows@main
        with:
            delete_releases: false
            delete_workflows: true
            workflows_keep_day: 0
            gh_token: ${{ secrets.GIT_TOKEN }}
